config/routes.rb
Rails.application.routes.draw do
  get 'save_data/index'

  get 'videos/new'

  get 'sesiones/new'


  root   'static_pages#inicio'
  #get    '/root_path', to: 'static_pages#inicio'
  get    '/nosotros',  to: 'static_pages#nosotros'
  get    '/ingresar',  to: 'sesiones#new'
  post   '/ingresar',  to: 'sesiones#create'
  get    '/contacto',  to: 'static_pages#contacto'
  get    '/registro',  to: 'usuarios#new'
  post   '/registro',  to: 'usuarios#create'
  get    '/ingreso',   to: 'sesiones#new'
  #  post   '/ingreso',   to: 'sesiones#create'
  delete '/salida',     to: 'sesiones#destroy'
  get    '/sites/:id', to: 'concursos#show'
  post   '/sites/:id', to: 'concursos#create'
  post   '/concursos/:id', to: 'concursos#edit'
  get   '/concursos/:id', to: 'concursos#show'
  resources :videos
  resources :usuarios
  resources :concursos, only: [:update, :create, :destroy]
end

app/models/video.rb
class Video < ApplicationRecord
  mount_uploader :video_source, VideoUploader # Tells rails to use this uploader for this model.
  belongs_to :concurso
  #after_create :run_workers

  validates :nombre, presence: true
  validates :apellido, presence: true
  validates :email, presence: true
  validates :titulo, presence: true
  validates :descripcion, presence: true
  validates :convirtiendo, :presence => false
  validates :estado, :presence => false
  validates :concurso_id, :presence => true

  private

  def run_workers
    Mp4VideoConverter.perform_async(self.id)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  include SesionesHelper
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.where(estado: false)
    .paginate(:page => params[:page], :per_page => 50)
    .order(created_at: :asc)
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])
  end

  # GET /videos/new
  def new
    concursos = []
    items = Aws.get_concursos
    items.each { |item|
      info = item['concurso_info']
      puts info['descripcion']
      puts item['concurso_info']
      puts item['concurso_id']
      puts item
      #@concurso
      concurso = Hash.new
      concurso[:nombre] = info['nombre']
      concurso[:fechaInicio] = info['fecha_inicio']
      concurso[:fechaFin] = info['fecha_fin']
      concurso[:descripcion] = info['descripcion']
      concurso[:id] = Integer(item['concurso_id'])
      puts concurso
      @concurso = Concurso.new(concurso)
      concursos.push(@concurso)
    }
    @concursos = concursos
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)
    video_id = DateTime.now.to_time.to_i
    nombre  = video_params['nombre']
    apellido = video_params['apellido']
    email = video_params['email']
    titulo = video_params['titulo']
    descripcion = video_params['descripcion']
    concurso_id = video_params['concurso_id']

    aws_params = Hash.new
    aws_params[:video_id] = video_id
    aws_params[:concurso_id] = concurso_id
    aws_params[:custom_fields]    = {
        'nombre'    => nombre,
        'apellido'   => apellido,
        'email' => email,
        'titulo' => titulo,
        'video' => @video.video_source.file.filename,
        'descripcion' => descripcion,
        'estado' => 0
    }
    respond_to do |format|
      if Aws.save_video_to_db(aws_params)
        uploader = VideoUploader.new
        uploader.store!(@video.video_source.file)
        sqs = Aws::SQS::Client.new(region: 'us-east-2')
        body = video_id.to_s + '-' + concurso_id.to_s + '-' +@video.video_source.file.filename
        sqs.send_message(queue_url: 'https://sqs.us-east-2.amazonaws.com/893543758111/smts-videos-queue', message_body: body)
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:nombre, :apellido, :email, :titulo, :descripcion, :video_source, :concurso_id) #, :ppath, :state
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true, :html => { :multipart => true }) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibite0d this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :apellido %>
    <%= form.text_field :apellido %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion %>
  </div>

  <div class="field">
    <%= form.label :video_source %>
    <%= form.file_field :video_source %>
  </div>

  <div class="field">
    <%= collection_select(:video, :concurso_id, @concursos, :id, :nombre, {:prompt => false}) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/videos/_video.html.erb
<li id="video-<%= video.id %>">
  <span class="concurso"><%= link_to @concurso.nombre, "/sites/"+@concurso.id.to_s %></span>
  <span class="video"><%= video.descripcion %></span>
  <%= jwplayer_assets %>
  <%= jwplayer({
        id: "jwplayer"+video.id.to_s,
        name: video.id,
        file: "https://s3.amazonaws.com/smarttoolsG5/public/upload/"+video.video_out.to_s,
        width: 500,
        height: 200
   }) %>
  <span class="timestamp">
    Posted <%= time_ago_in_words(video.created_at) %> ago.
  </span>
</li>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Videos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Title</th>
      <th>Description</th>
      <th>Opath</th>
      <th>Ppath</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.nombre %></td>
        <td><%= video.apellido %></td>
        <td><%= video.email %></td>
        <td><%= video.titulo %></td>
        <td><%= video.descripcion %></td>
        <td><%= video.video_source %></td>
        <td><%= video.video_out %></td>
        <td><%= video.estado %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @video.nombre %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @video.apellido %>
</p>

<p>
  <strong>Email:</strong>
  <%= @video.email %>
</p>

<p>
  <strong>Title:</strong>
  <%= @video.titulo %>
</p>

<p>
  <strong>Description:</strong>
  <%= @video.descripcion %>
</p>

<p>
  <strong>Opath:</strong>
  <%= @video.video_source %>
</p>

<p>
  <strong>Ppath:</strong>
  <%= @video.video_out %>
</p>

<p>
  <strong>State:</strong>
  <%= @video.estado %>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>