config/routes.rb
Rails.application.routes.draw do
  get 'save_data/index'

  get 'videos/new'

  get 'sesiones/new'


  root   'static_pages#inicio'
  #get    '/root_path', to: 'static_pages#inicio'
  get    '/nosotros',  to: 'static_pages#nosotros'
  get    '/ingresar',  to: 'sesiones#new'
  post   '/ingresar',  to: 'sesiones#create'
  get    '/contacto',  to: 'static_pages#contacto'
  get    '/registro',  to: 'usuarios#new'
  post   '/registro',  to: 'usuarios#create'
  get    '/ingreso',   to: 'sesiones#new'
  #  post   '/ingreso',   to: 'sesiones#create'
  delete '/salida',     to: 'sesiones#destroy'
  get    '/sites/:id', to: 'concursos#show'
  post   '/sites/:id', to: 'concursos#create'
  post   '/concursos/:id', to: 'concursos#edit'
  get   '/concursos/:id', to: 'concursos#show'
  resources :videos
  resources :usuarios
  resources :concursos, only: [:update, :create, :destroy]
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  has_many :concursos, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :nombre, presence: true, length: { maximum: 50 }
  validates :apellido, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 50 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

 
  def feed
    Concurso.where("usuario_id = ?", id)
  end

  def Usuario.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  include SesionesHelper
 # before_action :logged_in?, only: [:index, :edit, :update, :destroy]
  before_action :logged_in_usuario, only: [:show, :index, :edit, :update, :destroy]
  before_action :correct_user,   only:  [:edit, :update]
  before_action :admin_user, only: :destroy
  def show
    @usuario = Usuario.find(params[:id])
    puts 'showAct'
    puts @usuario.id
    concursos = []
    items = Aws.get_concursos_por_usuario(@usuario.id)
    items.each { |item|
        info = item['concurso_info']
        concurso = Hash.new
        concurso[:nombre] = info['nombre']
        concurso[:fechaInicio] = info['fecha_inicio']
        concurso[:fechaFin] = info['fecha_fin']
        concurso[:descripcion] = info['descripcion']
        concurso[:imagen] = info['imagen']
        concurso[:id] = Integer(item['concurso_id'])
        concurso[:usuario_id] = @usuario.id
        puts concurso
        @concurso = Concurso.new(concurso)
        concursos.push(@concurso)
    }
    @concursos = concursos
  end

  def index
    #@usuarios = Usuario.all
    @usuarios = Usuario.paginate(page: params[:page])
  end

  def new
    @usuario = Usuario.new 
  end

  def create
    @usuario = Usuario.new(usuario_params)
    if @usuario.save
      log_in @usuario
      flash[:success] = "Bienvenido a SmartTools!"
      redirect_to @usuario
    else
      render 'new'
    end
  end

  def edit
    @usuario = Usuario.find(params[:id])
  end

  def update
    @usuario = Usuario.find(params[:id])
    if @usuario.update_attributes(usuario_params)
      flash[:success] = "Perfil Actualizado"
      redirect_to @usuario
      # Handle a successful update.
    else
      render 'edit'
    end
  end
 
  def destroy
    Usuario.find(params[:id]).destroy
    flash[:success] = "Usuario Eliminado"
    redirect_to usuarios_url
  end





  private

  def usuario_params
      params.require(:usuario).permit(:nombre, :apellido, :email, :password, :password_confirmation)
  end

  # Before filters
    def logged_in_usuario
      unless logged_in?
        store_location
        flash[:danger] = "Por favor ingrese a la aplicación."
        redirect_to ingreso_url
      end
    end


  # Confirms the correct user.
  def correct_user
      @usuario = Usuario.find(params[:id])
      redirect_to(root_url) unless current_user?(@usuario)
  end

    # Confirms an admin user.
  def admin_user
      redirect_to(root_url) unless current_user.admin?
  end



end

app/helpers/usuarios_helper.rb
module UsuariosHelper
    # Returns the Gravatar for the given user.
  def gravatar_for(usuario, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(usuario.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: usuario.nombre, class: "gravatar")
  end
end

app/views/usuarios/_usuario.html.erb
<li>
      <%= gravatar_for usuario, size: 50 %>
      <%= link_to usuario.nombre+" "+ usuario.apellido, usuario %>
      
      <% if current_user.admin? && !current_user?(usuario) %>
         | <%= link_to "eliminar", usuario, method: :delete,
                                  data: { confirm: "Esta seguro?" } %>
      <% end %>


</li>

app/views/usuarios/edit.html.erb
<% provide(:title, "Editar usuario") %>
<h1>Actualizar su perfil</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@usuario) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :nombre %>
      <%= f.text_field :nombre, class: 'form-control' %>

      <%= f.label :apellido %>
      <%= f.text_field :apellido, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Guardas cambios", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @usuario %>
      <a href="http://gravatar.com/emails">change</a>
    </div>
  </div>
</div>

app/views/usuarios/index.html.erb
<% provide(:title, 'Todos los usuarios') %>
<h1>Todos los usuarios</h1>

<%= will_paginate %>

<ul class="usuarios">
  <%= render @usuarios %>

<!--
  <% @usuarios.each do |usuario| %>
     <%= render usuario %>

    <li>
      <%= gravatar_for usuario, size: 50 %>
      <%= link_to usuario.nombre+" "+ usuario.apellido, usuario %>
    </li>


  <% end %>
-->
</ul>

<%= will_paginate %>

app/views/usuarios/new.html.erb
<% provide(:title, 'registro') %>
<h1>Registro</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@usuario, url: registro_path) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.label :nombre %>
      <%= f.text_field :nombre, class: 'form-control' %>

      <%= f.label :apellido %>
      <%= f.text_field :apellido, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>


      <%= f.label :password_confirmation, "Confirmacion" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Crear mi cuenta", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/usuarios/show.html.erb
<% provide(:title, @usuario.nombre) %>
<div class="row">
  <aside class="col-md-6">
    <section class="user_info">
      <h1>
	<%= gravatar_for @usuario %>
        <%= @usuario.nombre %> <%= @usuario.apellido %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @concursos.any? %>
      <h3>Concursos (<%= @concursos.count %>)</h3>
      <ol class="concursos">
        <%= render @concursos %>
      </ol>
    <% end %>
  </div>

</div>