config/routes.rb
Rails.application.routes.draw do
  get 'save_data/index'

  get 'videos/new'

  get 'sesiones/new'


  root   'static_pages#inicio'
  #get    '/root_path', to: 'static_pages#inicio'
  get    '/nosotros',  to: 'static_pages#nosotros'
  get    '/ingresar',  to: 'sesiones#new'
  post   '/ingresar',  to: 'sesiones#create'
  get    '/contacto',  to: 'static_pages#contacto'
  get    '/registro',  to: 'usuarios#new'
  post   '/registro',  to: 'usuarios#create'
  get    '/ingreso',   to: 'sesiones#new'
  #  post   '/ingreso',   to: 'sesiones#create'
  delete '/salida',     to: 'sesiones#destroy'
  get    '/sites/:id', to: 'concursos#show'
  post   '/sites/:id', to: 'concursos#create'
  post   '/concursos/:id', to: 'concursos#edit'
  get   '/concursos/:id', to: 'concursos#show'
  resources :videos
  resources :usuarios
  resources :concursos, only: [:update, :create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://192.168.17.128/"> SmartTools.com </a>
    by <a href="http://192.168.17.128/">SmartTools Inc</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Nosotros",   '/nosotros' %></li>
      <li><%= link_to "Contactenos", '/contacto' %></li>
      <li><a href="http://moodleinstitucional.uniandes.edu.co/course/view.php?id=1202">Partners</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
   <%= link_to "SmartTools", 'root_path', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Inicio",   '/' %></li>
        <li><%= link_to "Nosotros",   '/nosotros' %></li>
        <li><%= link_to "Videos",   '/videos' %></li>
        
        <% if logged_in? %>
          <li><%= link_to "Usuarios", usuarios_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Cuenta <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Perfil", current_user %></li>
              <li><%= link_to "Settings", edit_usuario_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Salir", salida_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Ingresar", ingreso_path %></li>
        <% end %>

      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> | SmartTools</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>